openapi: 3.0.0
info:
  title: Snappy Shopper Test
  version: 1.0.0
servers:
  - url: http://localhost
  - url: http://127.0.0.1

paths:
  /api/add-store:
    post:
      tags:
        - default
      summary: Add store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Spar
                postcode: ZE10TY
                store_type: shop
                is_open: true
                max_delivery_distance: 5
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth_token
          in: header
          schema:
           type: string
          example: 12345
      responses:
        '200':
          description: Successful response to adding a new store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddStore'
        '422':
          description: Failure of form validation

  /api/search/stores/{store type}/{postcode}/{distance miles}:

    get:
      tags:
        - default
      summary: Stores that are within the search radius of a postcode.
      description: It is not to note that postcodes are to be entered without spaces and a store type when searching is to be between shop, takeaway, restaurant or all
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth_token
          in: header
          schema:
            type: string
          example: 12345
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResults'
  /api/search/delivery/store/S638EF/:
    get:
      tags:
        - default
      summary: can deliver too search
      description: It is not to note that postcodes are to be entered without spaces and a store type when searching is to be between shop, takeaway, restaurant or all
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth_token
          in: header
          schema:
            type: string
          example: 12345
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResults'
components:
  schemas:
    AddStore:
      type: object
      properties:
        store_id:
          type: integer
          example: 6

    SearchResults:
      type: object
      properties:
        current_page:
          type: integer
        data:
          type: array
        items:
          $ref: '#/components/schemas/Store'
        first_page_url:
          type: string
          format: uri
        from:
          type: integer
        last_page:
          type: integer
        last_page_url:
          type: string
          format: uri
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        next_page_url:
          type: string
          format: uri
          nullable: true
        path:
          type: string
          format: uri
        per_page:
          type: integer
        prev_page_url:
          type: string
          format: uri
          nullable: true
        to:
          type: integer
        total:
          type: integer

    Store:
      type: object
      properties:
        store_id:
          type: integer
        name:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        postcode:
          type: string
        is_open:
          type: boolean
        store_type:
          type: string
        max_delivery_distance:
          type: integer
        distance:
          type: number
          format: float

    Link:
      type: object
      properties:
        url:
          type: string
          format: uri
          nullable: true
        label:
          type: string
        active:
          type: boolean
